### ISSUE TITLE
[2JH] CI: Tests d'integrations

### ISSUE THREAD

**Issue by djnnvx** [vrn-sh/erp#51]
## Describe the issue
See the following [FIXME](https://github.com/vrn-sh/erp/blob/d8472447288118414c92ea9aaafdf26c934c8163/.github/workflows/compose.yml#L24)

When testing in CI if the services are correctly up, we should send a batch of requests. This is possible through [postman](https://www.postman.com/) by writing a set of [tests](https://learning.postman.com/docs/writing-scripts/test-scripts/).
One can then use the following service to test the requests: 
```yml
postman:
    container_name: outside-postman-container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: postman
    image: outside-postman-image
    depends_on:
      server:
        condition: service_healthy
    networks:
      - outside
```

With such `Dockerfile`:
```dockerfile
FROM node:alpine as postman

WORKDIR /app

RUN npm install -g newman

COPY . /app

CMD [ "newman", "run",  "Outside.postman_collection.json" ]
```

## Resource request
The question just is: From where should the tests be generated ? Perhaps there is a way to generate from `drf_yasg` ? Otherwise, a simple Python test script can be written and ran, but it should be written with simplicity and ease of maintainability in mind. 

## Definition of done
- [ ] explore a way to write tests for requests with reasoning for this choice
- [ ] implement the idea once validated by the team

## testing plan
- [ ] add to CI the testing of the API

## JEH
2
